# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghalint < Formula
  desc "GitHub Actions linter"
  homepage "https://github.com/suzuki-shunsuke/ghalint"
  version "0.2.12"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v0.2.12/ghalint_0.2.12_darwin_amd64.tar.gz"
      sha256 "8822612d7d7c5b9f01c7ad528e7b713f725befa9c632815d1303ce90f01bd4e7"

      def install
        bin.install "ghalint"
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v0.2.12/ghalint_0.2.12_darwin_arm64.tar.gz"
      sha256 "4b9f82d73da59b181a55a1aa2fdb4f1128b6ff4f4e4653407a5aac951cf8cf2a"

      def install
        bin.install "ghalint"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v0.2.12/ghalint_0.2.12_linux_amd64.tar.gz"
        sha256 "722d3420fff4f9a0d7b38b3654dfcddb4f1f6e2adbb3bba013f2d9eed406d9d5"

        def install
          bin.install "ghalint"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v0.2.12/ghalint_0.2.12_linux_arm64.tar.gz"
        sha256 "79c005fc8fccd220cef5da76a0c81a274abdf35a6db19e93ee731a43020b90ad"

        def install
          bin.install "ghalint"
        end
      end
    end
  end

  test do
    system "#{bin}/ghalint --version"
  end
end
