# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghalint < Formula
  desc "GitHub Actions linter"
  homepage "https://github.com/suzuki-shunsuke/ghalint"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v0.2.0/ghalint_0.2.0_darwin_amd64.tar.gz"
      sha256 "b3ee4418624caa98db36e90e8b0fbb1563f28b83dd8f23f18c5d9ee03507fd70"

      def install
        bin.install "ghalint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v0.2.0/ghalint_0.2.0_darwin_arm64.tar.gz"
      sha256 "4d8ddd0dfb7c1c36675970f8995386129d55be1db2220fedb09d2b761bbc8564"

      def install
        bin.install "ghalint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v0.2.0/ghalint_0.2.0_linux_arm64.tar.gz"
      sha256 "4825803d51be42b535b53bacd94929445f34fe3938d2be4c07b66cd08e91e939"

      def install
        bin.install "ghalint"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v0.2.0/ghalint_0.2.0_linux_amd64.tar.gz"
      sha256 "9992e9e964d77e60680e24162e563d6685dbe63f4a061b9cc6ee37a3c65c685a"

      def install
        bin.install "ghalint"
      end
    end
  end

  test do
    system "#{bin}/ghalint --version"
  end
end
