# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghalint" do
  version "1.5.6"

  on_macos do
    on_intel do
      sha256 "d2a0e8605333068065dcf4c9b7b7a24891eda1750ac01fb755dfba426a390883"
      url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v#{version}/ghalint_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1262cac411e27b4653e6b66b7b06580ebcc2026fdd903e12e6cb0e4591639de6"
      url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v#{version}/ghalint_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "98ee0e3330de7286f470d1e89c03ff7ce70d7a5998ba0f15969c400447be579c"
      url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v#{version}/ghalint_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "203a22c70b40bb161626973ad2a8dd06aeb736699fc8e03dd425dee8ff3406e6"
      url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v#{version}/ghalint_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ghalint"
  desc "GitHub Actions linter"
  homepage "https://github.com/suzuki-shunsuke/ghalint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghalint"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghalint"]
    end
  end

  # No zap stanza required

end
