# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghalint" do
  name "ghalint"
  desc "GitHub Actions linter"
  homepage "https://github.com/suzuki-shunsuke/ghalint"
  version "1.5.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghalint"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v#{version}/ghalint_#{version}_darwin_amd64.tar.gz"
      sha256 "ce76aeb46f051d19a618c4e89ae5ca1d37c5a06f1bac3afb261ff619fd33045f"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v#{version}/ghalint_#{version}_darwin_arm64.tar.gz"
      sha256 "db969e288fc788348aa7c1323096d69df28b457c70b4194fb76f14ad058c0be7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v#{version}/ghalint_#{version}_linux_amd64.tar.gz"
      sha256 "579cbf9024f86a8255ce8acdd56c7792f0f9a7e76063d64cfb7b66ff65c396e4"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v#{version}/ghalint_#{version}_linux_arm64.tar.gz"
      sha256 "c3ab464130015d733bfc75a2851f4fc5b3cb966aca2ed8bc0fa2a029bc0ee6af"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghalint"]
    end
  end

  # No zap stanza required
end
