# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghalint" do
  desc "GitHub Actions linter"
  homepage "https://github.com/suzuki-shunsuke/ghalint"
  version "1.5.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghalint"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v1.5.2/ghalint_1.5.2_darwin_amd64.tar.gz"
      sha256 "544134ba5579272de1d0a18db2a079cca8e1d4fc935a073f831e27b0b5dc2545"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v1.5.2/ghalint_1.5.2_darwin_arm64.tar.gz"
      sha256 "540436a69f9ef5e09d632d0c15e6b6335867e27df30ecffd1b159161c1b6e295"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v1.5.2/ghalint_1.5.2_linux_amd64.tar.gz"
      sha256 "01728c4cc69e7fd57162fc2970867973f9d618a38a7b798ce213eb27bdf8b9e1"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghalint/releases/download/v1.5.2/ghalint_1.5.2_linux_arm64.tar.gz"
      sha256 "ad0941950155e0c6ee3df839f9d8f5932c9b831a81ea3ea36f873ea562f85786"
    end
  end

  # No zap stanza required
end
